### ISSUE TITLE
Kernel timeout on new notebook

### ISSUE THREAD

**Issue by arnicas** [minrk/jskernel#4]
Hi again - interestingly, I can run your test notebook just fine - it loads, the cells execute, I can add new cells and execute just fine.  But when I try to create a new notebook with the js kernel, it hangs on starting the kernel and just says "Kernel starting, please wait..." Console window says just:

Kernel started: 05e29ae2-921a-42f5-a8fc-f218f5fa9adb
[W 10:40:12.311 NotebookApp] Timeout waiting for kernel_info reply from 05e29ae2-921a-42f5-a8fc-f218f5fa9adb

Any ideas on that?

**Comment by minrk** [comment]
ipython/ipython#7340 is merged, so I think this should be resolved. Feel free to reopen if the fix doesn't seem to work.
